theme: jekyll-theme-cayman
title: Robotics Work
author: emjayking
email: emjayking23@hotmail.co.nz
description:
  This is a portfolio of all my digital work
github_username: emjayking

show_excerpts: true
