theme: jekyll-theme-cayman
title: my port-folio
author: emjayking
email: emjayking23@hotmail.co.nz
description:
  These are certificates of completion for various coding languages.
github_username: emjayking

show_excerpts: true
