theme: jekyll-theme-cayman
title: My python work
author: emjayking
email: emjayking23@hotmail.co.nz
description:
  This is a collection of all my Python Codes
github_username: emjayking

show_excerpts: true
