theme: jekyll-theme-cayman
title: My metal models
author: emjayking
email: emjayking23@hotmail.co.nz
description:
  These are examples of some of my best work.
github_username: emjayking

show_excerpts: true
